#ifndef SHARED_UTILS_H
#define SHARED_UTILS_H

#include <string>
#include <vector>
#include <map>


enum XBOX360_AXES {
    XBOX_BTN_DPAD_UP = 0,
    XBOX_BTN_DPAD_DOWN = 1,
    XBOX_BTN_DPAD_LEFT = 2,
    XBOX_BTN_DPAD_RIGHT = 3,
    XBOX_BTN_START = 4,
    XBOX_BTN_BACK = 5,
    XBOX_BTN_LEFT_STICK = 6,        // Left stick click
    XBOX_BTN_RIGHT_STICK = 7,       // Right stick click
    XBOX_BTN_LEFT_BUMPER = 8,       // Left bumper
    XBOX_BTN_RIGHT_BUMPER = 9,      // Right bumper
    XBOX_BTN_GUIDE = 10,            // Home/Guide button
    XBOX_BTN_A = 12,
    XBOX_BTN_B = 13,
    XBOX_BTN_X = 14,
    XBOX_BTN_Y = 15,

    // Triggers (0-1000)
    XBOX_AXIS_LEFT_TRIGGER = 16,    // Left trigger
    XBOX_AXIS_RIGHT_TRIGGER = 17,   // Right trigger

    // Split axes - separate controls for each direction (0-1000 each)
    XBOX_AXIS_LX_MINUS = 18,   // Left stick X negative (left)
    XBOX_AXIS_LX_PLUS = 19,    // Left stick X positive (right)
    XBOX_AXIS_LY_MINUS = 20,   // Left stick Y negative (down)
    XBOX_AXIS_LY_PLUS = 21,    // Left stick Y positive (up)
    XBOX_AXIS_RX_MINUS = 22,   // Right stick X negative (left)
    XBOX_AXIS_RX_PLUS = 23,    // Right stick X positive (right)
    XBOX_AXIS_RY_MINUS = 24,   // Right stick Y negative (down)
    XBOX_AXIS_RY_PLUS = 25,    // Right stick Y positive (up)

    // Rumble event codes (for event callback)
    XBOX_RUMBLE_LEFT = 100,    // Left motor (large) - value 0-255
    XBOX_RUMBLE_RIGHT = 101    // Right motor (small) - value 0-255
};

enum MOUSE_AXES {
    MOUSE_AXIS_BUTTON_LEFT = 1,
    MOUSE_AXIS_BUTTON_RIGHT = 2,
    MOUSE_AXIS_BUTTON_MIDDLE = 3,
    MOUSE_AXIS_BUTTON_BACK = 4,
    MOUSE_AXIS_BUTTON_FORWARD = 5,
    MOUSE_AXIS_X_MINUS = 6,      // X Left
    MOUSE_AXIS_X_PLUS = 7,       // X Right
    MOUSE_AXIS_Y_MINUS = 8,      // Y Up
    MOUSE_AXIS_Y_PLUS = 9,       // Y Down
    MOUSE_AXIS_WHEEL_MINUS = 10,  // Wheel Down
    MOUSE_AXIS_WHEEL_PLUS = 11,   // Wheel Up
    MOUSE_AXIS_H_WHEEL_MINUS = 12, // H-Wheel Left
    MOUSE_AXIS_H_WHEEL_PLUS = 13,  // H-Wheel Right
    MOUSE_AXIS_XY = 14             // Combined signed X+Y packed in one int32: low16=X, high16=Y
};

// Gamepad axis bitmask flags (for HID descriptor configuration)
#define FLAG_MASK_GAMEPAD_AXIS_LX     0x01  // Bit 0: Left stick X
#define FLAG_MASK_GAMEPAD_AXIS_LY     0x02  // Bit 1: Left stick Y
#define FLAG_MASK_GAMEPAD_AXIS_LZ     0x04  // Bit 2: Left stick Z
#define FLAG_MASK_GAMEPAD_AXIS_RX     0x08  // Bit 3: Right stick X
#define FLAG_MASK_GAMEPAD_AXIS_RY     0x10  // Bit 4: Right stick Y
#define FLAG_MASK_GAMEPAD_AXIS_RZ     0x20  // Bit 5: Right stick Z
#define FLAG_MASK_GAMEPAD_AXIS_DIAL   0x40  // Bit 6: Dial
#define FLAG_MASK_GAMEPAD_AXIS_SLIDER 0x80  // Bit 7: Slider

enum HID_GAMEPAD_AXES {
    // Hat switch / D-pad (0-3)
    GAMEPAD_AXIS_HAT_UP = 0,
    GAMEPAD_AXIS_HAT_DOWN = 1,
    GAMEPAD_AXIS_HAT_LEFT = 2,
    GAMEPAD_AXIS_HAT_RIGHT = 3,

    // Buttons 1-32 (4-35)
    GAMEPAD_BTN_1 = 4,
    GAMEPAD_BTN_2 = 5,
    GAMEPAD_BTN_3 = 6,
    GAMEPAD_BTN_4 = 7,
    GAMEPAD_BTN_5 = 8,
    GAMEPAD_BTN_6 = 9,
    GAMEPAD_BTN_7 = 10,
    GAMEPAD_BTN_8 = 11,
    GAMEPAD_BTN_9 = 12,
    GAMEPAD_BTN_10 = 13,
    GAMEPAD_BTN_11 = 14,
    GAMEPAD_BTN_12 = 15,
    GAMEPAD_BTN_13 = 16,
    GAMEPAD_BTN_14 = 17,
    GAMEPAD_BTN_15 = 18,
    GAMEPAD_BTN_16 = 19,
    GAMEPAD_BTN_17 = 20,
    GAMEPAD_BTN_18 = 21,
    GAMEPAD_BTN_19 = 22,
    GAMEPAD_BTN_20 = 23,
    GAMEPAD_BTN_21 = 24,
    GAMEPAD_BTN_22 = 25,
    GAMEPAD_BTN_23 = 26,
    GAMEPAD_BTN_24 = 27,
    GAMEPAD_BTN_25 = 28,
    GAMEPAD_BTN_26 = 29,
    GAMEPAD_BTN_27 = 30,
    GAMEPAD_BTN_28 = 31,
    GAMEPAD_BTN_29 = 32,
    GAMEPAD_BTN_30 = 33,
    GAMEPAD_BTN_31 = 34,
    GAMEPAD_BTN_32 = 35,

    // Axes - split into negative and positive directions (36-51)
    GAMEPAD_AXIS_LX_MINUS = 36,    // Left stick X negative (left)
    GAMEPAD_AXIS_LX_PLUS = 37,     // Left stick X positive (right)
    GAMEPAD_AXIS_LY_MINUS = 38,    // Left stick Y negative (down)
    GAMEPAD_AXIS_LY_PLUS = 39,     // Left stick Y positive (up)
    GAMEPAD_AXIS_LZ_MINUS = 40,    // Left stick Z negative
    GAMEPAD_AXIS_LZ_PLUS = 41,     // Left stick Z positive
    GAMEPAD_AXIS_RX_MINUS = 42,    // Right stick X negative (left)
    GAMEPAD_AXIS_RX_PLUS = 43,     // Right stick X positive (right)
    GAMEPAD_AXIS_RY_MINUS = 44,    // Right stick Y negative (down)
    GAMEPAD_AXIS_RY_PLUS = 45,     // Right stick Y positive (up)
    GAMEPAD_AXIS_RZ_MINUS = 46,    // Right stick Z negative
    GAMEPAD_AXIS_RZ_PLUS = 47,     // Right stick Z positive
    GAMEPAD_AXIS_DIAL_MINUS = 48,  // Dial negative
    GAMEPAD_AXIS_DIAL_PLUS = 49,   // Dial positive
    GAMEPAD_AXIS_SLIDER_MINUS = 50,// Slider negative
    GAMEPAD_AXIS_SLIDER_PLUS = 51  // Slider positive
};

enum KEYBOARD_AXES {
    KEYBOARD_KEY_UNUSED_0 = 0,
    KEYBOARD_KEY_UNUSED_1 = 1,
    KEYBOARD_KEY_UNUSED_2 = 2,
    KEYBOARD_KEY_UNUSED_3 = 3,
    KEYBOARD_KEY_UNUSED_4 = 4,
    KEYBOARD_KEY_A = 5,
    KEYBOARD_KEY_B = 6,
    KEYBOARD_KEY_C = 7,
    KEYBOARD_KEY_D = 8,
    KEYBOARD_KEY_E = 9,
    KEYBOARD_KEY_F = 10,
    KEYBOARD_KEY_G = 11,
    KEYBOARD_KEY_H = 12,
    KEYBOARD_KEY_I = 13,
    KEYBOARD_KEY_J = 14,
    KEYBOARD_KEY_K = 15,
    KEYBOARD_KEY_L = 16,
    KEYBOARD_KEY_M = 17,
    KEYBOARD_KEY_N = 18,
    KEYBOARD_KEY_O = 19,
    KEYBOARD_KEY_P = 20,
    KEYBOARD_KEY_Q = 21,
    KEYBOARD_KEY_R = 22,
    KEYBOARD_KEY_S = 23,
    KEYBOARD_KEY_T = 24,
    KEYBOARD_KEY_U = 25,
    KEYBOARD_KEY_V = 26,
    KEYBOARD_KEY_W = 27,
    KEYBOARD_KEY_X = 28,
    KEYBOARD_KEY_Y = 29,
    KEYBOARD_KEY_Z = 30,
    KEYBOARD_KEY_1 = 31,
    KEYBOARD_KEY_2 = 32,
    KEYBOARD_KEY_3 = 33,
    KEYBOARD_KEY_4 = 34,
    KEYBOARD_KEY_5 = 35,
    KEYBOARD_KEY_6 = 36,
    KEYBOARD_KEY_7 = 37,
    KEYBOARD_KEY_8 = 38,
    KEYBOARD_KEY_9 = 39,
    KEYBOARD_KEY_0 = 40,
    KEYBOARD_KEY_ENTER = 41,
    KEYBOARD_KEY_ESCAPE = 42,
    KEYBOARD_KEY_BACKSPACE = 43,
    KEYBOARD_KEY_TAB = 44,
    KEYBOARD_KEY_SPACE = 45,
    KEYBOARD_KEY_MINUS = 46,
    KEYBOARD_KEY_EQUAL = 47,
    KEYBOARD_KEY_BRACKET_LEFT = 48,
    KEYBOARD_KEY_BRACKET_RIGHT = 49,
    KEYBOARD_KEY_BACKSLASH = 50,
    KEYBOARD_KEY_EUROPE_1 = 51,
    KEYBOARD_KEY_SEMICOLON = 52,
    KEYBOARD_KEY_APOSTROPHE = 53,
    KEYBOARD_KEY_GRAVE = 54,
    KEYBOARD_KEY_COMMA = 55,
    KEYBOARD_KEY_PERIOD = 56,
    KEYBOARD_KEY_SLASH = 57,
    KEYBOARD_KEY_CAPS_LOCK = 58,
    KEYBOARD_KEY_F1 = 59,
    KEYBOARD_KEY_F2 = 60,
    KEYBOARD_KEY_F3 = 61,
    KEYBOARD_KEY_F4 = 62,
    KEYBOARD_KEY_F5 = 63,
    KEYBOARD_KEY_F6 = 64,
    KEYBOARD_KEY_F7 = 65,
    KEYBOARD_KEY_F8 = 66,
    KEYBOARD_KEY_F9 = 67,
    KEYBOARD_KEY_F10 = 68,
    KEYBOARD_KEY_F11 = 69,
    KEYBOARD_KEY_F12 = 70,
    KEYBOARD_KEY_PRINT_SCREEN = 71,
    KEYBOARD_KEY_SCROLL_LOCK = 72,
    KEYBOARD_KEY_PAUSE = 73,
    KEYBOARD_KEY_INSERT = 74,
    KEYBOARD_KEY_HOME = 75,
    KEYBOARD_KEY_PAGE_UP = 76,
    KEYBOARD_KEY_DELETE = 77,
    KEYBOARD_KEY_END = 78,
    KEYBOARD_KEY_PAGE_DOWN = 79,
    KEYBOARD_KEY_ARROW_RIGHT = 80,
    KEYBOARD_KEY_ARROW_LEFT = 81,
    KEYBOARD_KEY_ARROW_DOWN = 82,
    KEYBOARD_KEY_ARROW_UP = 83,
    KEYBOARD_KEY_NUM_LOCK = 84,
    KEYBOARD_KEY_KEYPAD_DIVIDE = 85,
    KEYBOARD_KEY_KEYPAD_MULTIPLY = 86,
    KEYBOARD_KEY_KEYPAD_SUBTRACT = 87,
    KEYBOARD_KEY_KEYPAD_ADD = 88,
    KEYBOARD_KEY_KEYPAD_ENTER = 89,
    KEYBOARD_KEY_KEYPAD_1 = 90,
    KEYBOARD_KEY_KEYPAD_2 = 91,
    KEYBOARD_KEY_KEYPAD_3 = 92,
    KEYBOARD_KEY_KEYPAD_4 = 93,
    KEYBOARD_KEY_KEYPAD_5 = 94,
    KEYBOARD_KEY_KEYPAD_6 = 95,
    KEYBOARD_KEY_KEYPAD_7 = 96,
    KEYBOARD_KEY_KEYPAD_8 = 97,
    KEYBOARD_KEY_KEYPAD_9 = 98,
    KEYBOARD_KEY_KEYPAD_0 = 99,
    KEYBOARD_KEY_KEYPAD_DECIMAL = 100,
    KEYBOARD_KEY_EUROPE_2 = 101,
    KEYBOARD_KEY_APPLICATION = 102,
    KEYBOARD_KEY_POWER = 103,
    KEYBOARD_KEY_KEYPAD_EQUAL = 104,
    KEYBOARD_KEY_F13 = 105,
    KEYBOARD_KEY_F14 = 106,
    KEYBOARD_KEY_F15 = 107,
    KEYBOARD_KEY_F16 = 108,
    KEYBOARD_KEY_F17 = 109,
    KEYBOARD_KEY_F18 = 110,
    KEYBOARD_KEY_F19 = 111,
    KEYBOARD_KEY_F20 = 112,
    KEYBOARD_KEY_F21 = 113,
    KEYBOARD_KEY_F22 = 114,
    KEYBOARD_KEY_F23 = 115,
    KEYBOARD_KEY_F24 = 116,
    KEYBOARD_KEY_EXECUTE = 117,
    KEYBOARD_KEY_HELP = 118,
    KEYBOARD_KEY_MENU = 119,
    KEYBOARD_KEY_SELECT = 120,
    KEYBOARD_KEY_STOP = 121,
    KEYBOARD_KEY_AGAIN = 122,
    KEYBOARD_KEY_UNDO = 123,
    KEYBOARD_KEY_CUT = 124,
    KEYBOARD_KEY_COPY = 125,
    KEYBOARD_KEY_PASTE = 126,
    KEYBOARD_KEY_FIND = 127,
    KEYBOARD_KEY_MUTE = 128,
    KEYBOARD_KEY_VOLUME_UP = 129,
    KEYBOARD_KEY_VOLUME_DOWN = 130,
    KEYBOARD_KEY_LOCKING_CAPS_LOCK = 131,
    KEYBOARD_KEY_LOCKING_NUM_LOCK = 132,
    KEYBOARD_KEY_LOCKING_SCROLL_LOCK = 133,
    KEYBOARD_KEY_KEYPAD_COMMA = 134,
    KEYBOARD_KEY_KEYPAD_EQUAL_SIGN = 135,
    KEYBOARD_KEY_KANJI1 = 136,
    KEYBOARD_KEY_KANJI2 = 137,
    KEYBOARD_KEY_KANJI3 = 138,
    KEYBOARD_KEY_KANJI4 = 139,
    KEYBOARD_KEY_KANJI5 = 140,
    KEYBOARD_KEY_KANJI6 = 141,
    KEYBOARD_KEY_KANJI7 = 142,
    KEYBOARD_KEY_KANJI8 = 143,
    KEYBOARD_KEY_KANJI9 = 144,
    KEYBOARD_KEY_LANG1 = 145,
    KEYBOARD_KEY_LANG2 = 146,
    KEYBOARD_KEY_LANG3 = 147,
    KEYBOARD_KEY_LANG4 = 148,
    KEYBOARD_KEY_LANG5 = 149,
    KEYBOARD_KEY_LANG6 = 150,
    KEYBOARD_KEY_LANG7 = 151,
    KEYBOARD_KEY_LANG8 = 152,
    KEYBOARD_KEY_LANG9 = 153,
    KEYBOARD_KEY_ALTERNATE_ERASE = 154,
    KEYBOARD_KEY_SYSREQ_ATTENTION = 155,
    KEYBOARD_KEY_CANCEL = 156,
    KEYBOARD_KEY_CLEAR = 157,
    KEYBOARD_KEY_PRIOR = 158,
    KEYBOARD_KEY_RETURN = 159,
    KEYBOARD_KEY_SEPARATOR = 160,
    KEYBOARD_KEY_OUT = 161,
    KEYBOARD_KEY_OPER = 162,
    KEYBOARD_KEY_CLEAR_AGAIN = 163,
    KEYBOARD_KEY_CRSEL_PROPS = 164,
    KEYBOARD_KEY_EXSEL = 165,
    KEYBOARD_KEY_UNUSED_165 = 166,
    KEYBOARD_KEY_UNUSED_166 = 167,
    KEYBOARD_KEY_UNUSED_167 = 168,
    KEYBOARD_KEY_UNUSED_168 = 169,
    KEYBOARD_KEY_UNUSED_169 = 170,
    KEYBOARD_KEY_UNUSED_170 = 171,
    KEYBOARD_KEY_UNUSED_171 = 172,
    KEYBOARD_KEY_UNUSED_172 = 173,
    KEYBOARD_KEY_UNUSED_173 = 174,
    KEYBOARD_KEY_UNUSED_174 = 175,
    KEYBOARD_KEY_UNUSED_175 = 176,
    KEYBOARD_KEY_KEYPAD_00 = 177,
    KEYBOARD_KEY_KEYPAD_000 = 178,
    KEYBOARD_KEY_THOUSANDS_SEPARATOR = 179,
    KEYBOARD_KEY_DECIMAL_SEPARATOR = 180,
    KEYBOARD_KEY_CURRENCY_UNIT = 181,
    KEYBOARD_KEY_CURRENCY_SUBUNIT = 182,
    KEYBOARD_KEY_KEYPAD_LEFT_PARENTHESIS = 183,
    KEYBOARD_KEY_KEYPAD_RIGHT_PARENTHESIS = 184,
    KEYBOARD_KEY_KEYPAD_LEFT_BRACE = 185,
    KEYBOARD_KEY_KEYPAD_RIGHT_BRACE = 186,
    KEYBOARD_KEY_KEYPAD_TAB = 187,
    KEYBOARD_KEY_KEYPAD_BACKSPACE = 188,
    KEYBOARD_KEY_KEYPAD_A = 189,
    KEYBOARD_KEY_KEYPAD_B = 190,
    KEYBOARD_KEY_KEYPAD_C = 191,
    KEYBOARD_KEY_KEYPAD_D = 192,
    KEYBOARD_KEY_KEYPAD_E = 193,
    KEYBOARD_KEY_KEYPAD_F = 194,
    KEYBOARD_KEY_KEYPAD_XOR = 195,
    KEYBOARD_KEY_KEYPAD_CARET = 196,
    KEYBOARD_KEY_KEYPAD_PERCENT = 197,
    KEYBOARD_KEY_KEYPAD_LESS_THAN = 198,
    KEYBOARD_KEY_KEYPAD_GREATER_THAN = 199,
    KEYBOARD_KEY_KEYPAD_AMPERSAND = 200,
    KEYBOARD_KEY_KEYPAD_DOUBLE_AMPERSAND = 201,
    KEYBOARD_KEY_KEYPAD_VERTICAL_BAR = 202,
    KEYBOARD_KEY_KEYPAD_DOUBLE_VERTICAL_BAR = 203,
    KEYBOARD_KEY_KEYPAD_COLON = 204,
    KEYBOARD_KEY_KEYPAD_HASH = 205,
    KEYBOARD_KEY_KEYPAD_SPACE = 206,
    KEYBOARD_KEY_KEYPAD_AT = 207,
    KEYBOARD_KEY_KEYPAD_EXCLAMATION = 208,
    KEYBOARD_KEY_KEYPAD_MEMORY_STORE = 209,
    KEYBOARD_KEY_KEYPAD_MEMORY_RECALL = 210,
    KEYBOARD_KEY_KEYPAD_MEMORY_CLEAR = 211,
    KEYBOARD_KEY_KEYPAD_MEMORY_ADD = 212,
    KEYBOARD_KEY_KEYPAD_MEMORY_SUBTRACT = 213,
    KEYBOARD_KEY_KEYPAD_MEMORY_MULTIPLY = 214,
    KEYBOARD_KEY_KEYPAD_MEMORY_DIVIDE = 215,
    KEYBOARD_KEY_KEYPAD_PLUS_MINUS = 216,
    KEYBOARD_KEY_KEYPAD_CLEAR = 217,
    KEYBOARD_KEY_KEYPAD_CLEAR_ENTRY = 218,
    KEYBOARD_KEY_KEYPAD_BINARY = 219,
    KEYBOARD_KEY_KEYPAD_OCTAL = 220,
    KEYBOARD_KEY_KEYPAD_DECIMAL_2 = 221,
    KEYBOARD_KEY_KEYPAD_HEXADECIMAL = 222,
    KEYBOARD_KEY_UNUSED_222 = 223,
    KEYBOARD_KEY_UNUSED_223 = 224,
    KEYBOARD_KEY_CONTROL_LEFT = 225,
    KEYBOARD_KEY_SHIFT_LEFT = 226,
    KEYBOARD_KEY_ALT_LEFT = 227,
    KEYBOARD_KEY_GUI_LEFT = 228,
    KEYBOARD_KEY_CONTROL_RIGHT = 229,
    KEYBOARD_KEY_SHIFT_RIGHT = 230,
    KEYBOARD_KEY_ALT_RIGHT = 231,
    KEYBOARD_KEY_GUI_RIGHT = 232,
    KEYBOARD_KEY_UNUSED_232 = 233,
    KEYBOARD_KEY_UNUSED_233 = 234,
    KEYBOARD_KEY_UNUSED_234 = 235,
    KEYBOARD_KEY_UNUSED_235 = 236,
    KEYBOARD_KEY_UNUSED_236 = 237,
    KEYBOARD_KEY_UNUSED_237 = 238,
    KEYBOARD_KEY_UNUSED_238 = 239,
    KEYBOARD_KEY_UNUSED_239 = 240,
    KEYBOARD_KEY_UNUSED_240 = 241,
    KEYBOARD_KEY_UNUSED_241 = 242,
    KEYBOARD_KEY_UNUSED_242 = 243,
    KEYBOARD_KEY_UNUSED_243 = 244,
    KEYBOARD_KEY_UNUSED_244 = 245,
    KEYBOARD_KEY_UNUSED_245 = 246,
    KEYBOARD_KEY_UNUSED_246 = 247,
    KEYBOARD_KEY_UNUSED_247 = 248,
    KEYBOARD_KEY_UNUSED_248 = 249,
    KEYBOARD_KEY_UNUSED_249 = 250,
    KEYBOARD_KEY_UNUSED_250 = 251,
    KEYBOARD_KEY_UNUSED_251 = 252,
    KEYBOARD_KEY_UNUSED_252 = 253,
    KEYBOARD_KEY_UNUSED_253 = 254,
    KEYBOARD_KEY_UNUSED_254 = 255,
    KEYBOARD_KEY_UNUSED_255 = 256
};

extern const char* HID_GAMEPAD_AXES_NAMES[52];
extern const char* XBOX360_AXES_NAMES[26];
extern const char* MOUSE_AXES_NAMES[16];
extern const char* KEYBOARD_AXES_NAMES[258];


enum DeviceMode {
    HID_MODE = 0,      // Keyboard + Mouse + HID Gamepads (DEFAULT)
    XINPUT_MODE = 1    // XInput Gamepads only (Xbox 360)
};

// A single axis entry: human-readable name and its integer index (from the enums above)
struct AxisEntry {
    std::string name;
    int index;
};

// Bidirectional name<->index table for a device type.
// For emulated devices it is built from the shared *_NAMES arrays.
// For real devices it is built dynamically from evdev capabilities.
class AxisTable {
public:
    void addEntry(const std::string& name, int index);

    // Returns -1 if name not found
    int getIndex(const std::string& name) const;

    // Returns empty string if index not found
    std::string getName(int index) const;

    bool hasName(const std::string& name) const;
    bool hasIndex(int index) const;

    const std::vector<AxisEntry>& getEntries() const { return entries; }

    // Build static tables from the shared *_NAMES arrays
    static AxisTable forHidGamepad();
    static AxisTable forXbox360();
    static AxisTable forMouse();
    static AxisTable forKeyboard();

private:
    std::vector<AxisEntry> entries;
    std::map<std::string, int> nameToIndex;
    std::map<int, std::string> indexToName;
};

#endif // SHARED_UTILS_H